In [13]:
import pandas as pd
data = pd.read_csv("Dataset_pandas.csv")
data

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115.0,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100.0,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114.0,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114.0,23,13415.0

In [14]:
data.iloc[:, 0]

0      0
1      1
2      2
3      3
4      4
      ..
56    81
57    82
58    86
59    87
60    88
Name: index, Length: 61, dtype: int64

In [16]:
data.iloc[:, 1]

0     alfa-romero
1     alfa-romero
2     alfa-romero
3            audi
4            audi
         ...
56     volkswagen
57     volkswagen
58     volkswagen
59          volvo
60          volvo
Name: company, Length: 61, dtype: object

In [18]:
data.iloc[1]

index                         1
company             alfa-romero
body-style          convertible
wheel-base                 88.6
length                    168.8
engine-type                dohc
num-of-cylinders           four
horsepower                111.0
average-mileage              21
price                   16500.0
Name: 1, dtype: object

In [19]:
y = data.iloc[:, -1]
y

0     13495.0
1     16500.0
2     16500.0
3     13950.0
4     17450.0
       ...
56     7975.0
57     7995.0
58     9995.0
59    12940.0
60    13415.0
Name: price, Length: 61, dtype: float64

In [20]:

x = data.iloc[:, :-1]
x

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,19
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24
4,4,audi,sedan,99.4,176.6,ohc,five,115.0,18
...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100.0,26
59,87,volvo,sedan,104.3,188.8,ohc,four,114.0,23
60,88,volvo,wagon,104.3,188.8,ohc,four,114.0,23

In [21]:
y.shape

(61,)

In [22]:
x = data.iloc[:, :-3]
x

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders
0,0,alfa-romero,convertible,88.6,168.8,dohc,four
1,1,alfa-romero,convertible,88.6,168.8,dohc,four
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six
3,3,audi,sedan,99.8,176.6,ohc,four
4,4,audi,sedan,99.4,176.6,ohc,five
...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four
57,82,volkswagen,sedan,97.3,171.7,ohc,four
58,86,volkswagen,sedan,97.3,171.7,ohc,four
59,87,volvo,sedan,104.3,188.8,ohc,four
60,88,volvo,wagon,104.3,188.8,ohc,four

In [23]:
data.iloc[:5]

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115.0,18,17450.0

In [24]:
data.iloc[:3, :2]

   index      company
0      0  alfa-romero
1      1  alfa-romero
2      2  alfa-romero

In [25]:
data.iloc[:, :3]

    index      company   body-style
0       0  alfa-romero  convertible
1       1  alfa-romero  convertible
2       2  alfa-romero    hatchback
3       3         audi        sedan
4       4         audi        sedan
..    ...          ...          ...
56     81   volkswagen        sedan
57     82   volkswagen        sedan
58     86   volkswagen        sedan
59     87        volvo        sedan
60     88        volvo        wagon

[61 rows x 3 columns]

In [26]:
data.iloc[0]

index                         0
company             alfa-romero
body-style          convertible
wheel-base                 88.6
length                    168.8
engine-type                dohc
num-of-cylinders           four
horsepower                111.0
average-mileage              21
price                   13495.0
Name: 0, dtype: object

In [27]:
data.iloc[-1]

index                    88
company               volvo
body-style            wagon
wheel-base            104.3
length                188.8
engine-type             ohc
num-of-cylinders       four
horsepower            114.0
average-mileage          23
price               13415.0
Name: 60, dtype: object